// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr2uEu4m35mO8rvGCf5wYAMBz8W0eKdMM',
    appId: '1:768710015329:web:3fe1d064af8a35b43ced20',
    messagingSenderId: '768710015329',
    projectId: 'fir-test-8843d',
    authDomain: 'fir-test-8843d.firebaseapp.com',
    storageBucket: 'fir-test-8843d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLw9jTP28EAy1xyNJjMjlvmSjyRAedMlA',
    appId: '1:768710015329:android:ad816e9f73482ac03ced20',
    messagingSenderId: '768710015329',
    projectId: 'fir-test-8843d',
    storageBucket: 'fir-test-8843d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPhJL-rOeGl-nft5oXmyaeoLhgceQ9p64',
    appId: '1:768710015329:ios:e7e2b02f061f15d33ced20',
    messagingSenderId: '768710015329',
    projectId: 'fir-test-8843d',
    storageBucket: 'fir-test-8843d.firebasestorage.app',
    iosBundleId: 'com.example.basicFlutterTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPhJL-rOeGl-nft5oXmyaeoLhgceQ9p64',
    appId: '1:768710015329:ios:e7e2b02f061f15d33ced20',
    messagingSenderId: '768710015329',
    projectId: 'fir-test-8843d',
    storageBucket: 'fir-test-8843d.firebasestorage.app',
    iosBundleId: 'com.example.basicFlutterTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr2uEu4m35mO8rvGCf5wYAMBz8W0eKdMM',
    appId: '1:768710015329:web:62377505df6dcfbd3ced20',
    messagingSenderId: '768710015329',
    projectId: 'fir-test-8843d',
    authDomain: 'fir-test-8843d.firebaseapp.com',
    storageBucket: 'fir-test-8843d.firebasestorage.app',
  );
}
